### ISSUE TITLE
Support transition from 'Any'

### ISSUE THREAD

**Issue by dawidgorny** [choojs/nanostate#14]
Hi,

I wanted to propose a feature which I found very handy. 

Inspired by a state machine in Unity where you can define transitions from 'Any'. This way you can avoid repetition if there is some set of transitions always available no matter in which state we are.

```
const machine = nanostate('idle', {
  '_any': { 
    'reset': 'idle'
  },
  'idle': { go: 'state1' }
  'state1': {  }

  // ...

}
```
I created a draft PR: https://github.com/choojs/nanostate/pull/13

**Comment by goto-bus-stop** [comment]
seems nice. maybe we can use the `'*'` for the "catchall" name, similar to [nanobus](https://github.com/choojs/nanobus/#busoneventname-listenerdata)?

**Comment by dawidgorny** [comment]
@goto-bus-stop yeah, good idea. I like `'*'`.
