### ISSUE TITLE
implementation of hierarchical state 

### ISSUE THREAD

**Issue by kareniel** [choojs/nanostate#2]
did some exploring of a possible implementation of hierarchical state.
it's over here: https://github.com/kareniel/nanostate/tree/hierarchical

there's also a little demo in the branch ( `npm run example` ). 
i'm thinking it could eventually be recycled into some docs ¯\\_(ツ)_/¯

*ps: it's definitely not production ready*

**Comment by yoshuawuyts** [comment]
@kareniel oh sick - I totally missed this; but this is great!

Would you be willing to make a PR, perhaps with a test for this? I'm kinda getting back into this, and it'd be great to advance :D
